version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.5-browsers
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: bob-style-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: npm install bob-style --no-save
      - save_cache:
          key: bob-style-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # run tests!
      #npm run to run ng because @angular/cli is not installed globally.

      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadless
      # - run: npm run build-storybook
      - store_test_results:
          path: ~/repo/test-results/
      - store_artifacts:
          path: ~/repo/test-results/
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:12.5
    working_directory: ~/repo
    parameters:
      bobStylePackageJson: './projects/ui-framework/package.json'
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .

      # deploy!
      - run: mkdir -p .out/.circleci && cp -a .circleci/. .out/.circleci/.
      #- run: npm run build-storybook
      #- run: npm run deploy-storybook --  --existing-output-dir=.out --ci --host-token-env-variable=GITHUB_TOKEN

      #deploy to npm
      - run:
          name: 'Bump version locally'
          command: |
            cd ./projects/ui-framework
            npm version patch --no-git-tag-version
            cd ../..
      - run: npm run package
      - run:
          name: 'Deploy to npm'
          command: |
            echo "registry=https://hibob.jfrog.io/hibob/api/npm/bob-js-virtual/
            _auth = ${JFROG_NPM_TOKEN}
            always-auth = true
            email = deploy-js@hibob.io" > .npmrc
            npm publish ./dist/ui-framework/*.tgz --scope=hibob
      - run:
          name: 'Commit new version'
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "bot@hibob.io"
            git config user.name "Deployment Bot"
            git add .
            git commit --allow-empty -m "bump version [skip ci]"
            git push -q https://${GITHUB_TOKEN}@github.com/hibobio/bob-style.git master

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
