name: master workflow

on:
  push:
    branches:
      - master
env:
  CI_COMMITTER_NAME: ${{github.actor}}
  CI_BRANCH: ${{github.ref}}
jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: jfrog
        run: printf "registry=https://hibob.jfrog.io/hibob/api/npm/bob-js-virtual/\n_auth = ${{ secrets.JFROG_NPM_TOKEN }}\nalways-auth = true\nemail = deploy-js@hibob.io" > .npmrc
        shell: bash
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: npm install
        run: npm ci
      - name: install bob-style
        run: npm install bob-style --no-save
      - name: build storybook
        run: npm run build-storybook
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: .out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

  publich-bob-style-library:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: jfrog
        run: printf "registry=https://hibob.jfrog.io/hibob/api/npm/bob-js-virtual/\n_auth = ${{ secrets.JFROG_NPM_TOKEN }}\nalways-auth = true\nemail = deploy-js@hibob.io" > .npmrc
        shell: bash
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Commit test
        run: |
          date > generated.txt
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "bumo version"
          git push -q https://bot:${{secrets.GITHUB_TOKEN}}@github.com/hibobio/bob-style.git master

      - name: npm install
        run: npm ci
      - name: Bump version locally
        run: |
          cd ./projects/ui-framework
          npm version patch --no-git-tag-version
          cd ../..
      - name: package
        run: npm run package
      - name: Deploy to npm ðŸš€
        run: npm publish ./dist/ui-framework/*.tgz --scope=hibob
      - name: Commit new version changes
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "bumo version"
          git push
